version: '3.1'
services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
    volumes:
      - superset_home:/app/superset_home
    restart: always

volumes:
  superset_home:
